### ISSUE TITLE
project fails when building github actions with NodeJS v12

### ISSUE THREAD

**Issue by thescientist13** [thegreenhouseio/www.thegreenhouse.io#146]
Added GitHub Actions and then the [`0.5.0`](https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/132) release branch started failing. 😞  
https://github.com/thegreenhouseio/www.thegreenhouse.io/runs/816494978?check_suite_focus=true
```
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/@babel/core/lib/index.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/babel-loader/lib/index.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/loader-runner/lib/loadLoader.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/loader-runner/lib/LoaderRunner.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/webpack/lib/NormalModule.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/webpack/lib/NormalModuleFactory.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/webpack/lib/Compiler.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/webpack/lib/webpack.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/@greenwood/cli/src/tasks/build.js
- /home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/@greenwood/cli/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/work/www.thegreenhouse.io/www.thegreenhouse.io/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

Downgrading to 10.x worked 🤔 
* https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/132/commits/8b049fbb9f02fd97853dd79fcbbd51c86292d74d
* https://github.com/thegreenhouseio/www.thegreenhouse.io/actions/runs/150926070

**Comment by thescientist13** [comment]
Welp, [when pinned to 12.13.0](https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/132/commits/aee4c7f441b494b65cd3a4bf8c6c0f715f141955), which workdc for me locally, it works in [GitHub Actions](https://github.com/thegreenhouseio/www.thegreenhouse.io/actions/runs/151956941) now too.  Must be something in whatever version is getting pulled down when using `12.x`.  🤷‍♂️
