### ISSUE TITLE
add ability to deep link to a section of the about page

### ISSUE THREAD

**Issue by thescientist13** [thegreenhouseio/www.thegreenhouse.io#203]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
The about page currently has to sections, one for writing and one for speaking.  It would be nice if loading something like this would work
```
http://www.thegreenhouse.io/about/?tab=writing

http://www.thegreenhouse.io/about/#writing
```

## Details
Either or would be good.

**Comment by thescientist13** [comment]
It seems that when using a query sting, dev server (specifically **plugin-graphql**) barfs?  🤔 
http://localhost:51201?tab=home
```sh
% yarn develop
yarn run v1.12.3
$ greenwood develop
-------------------------------------------------------
Welcome to Greenwood ♻️
-------------------------------------------------------
Running Greenwood with the develop command.
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
Started local development server at localhost:51201
GraphQLServer started at http://localhost:4000/

  TypeError: Cannot read property 'indexOf' of undefined
      at /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/plugin-graphql/src/index.js:41:36
      at new Promise (<anonymous>)
      at GraphQLResource.intercept (/Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/plugin-graphql/src/index.js:38:12)
      at /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/cli/src/lifecycles/serve.js:118:52
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/cli/src/lifecycles/serve.js:109:24
      at async /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/cli/src/lifecycles/serve.js:108:29
      at async /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/cli/src/lifecycles/serve.js:95:5
      at async /Users/owenbuckley/Workspace/thegreenhouse.io/repo/www.thegreenhouse.io/node_modules/@greenwood/cli/src/lifecycles/serve.js:58:5
```

<img width="835" alt="Screen Shot 2021-04-25 at 7 58 00 PM" src="https://user-images.githubusercontent.com/895923/116013914-adbd3080-a600-11eb-9a78-b50d4d8e6228.png">
