### ISSUE TITLE
build failing on CloudFront invalidation

### ISSUE THREAD

**Issue by thescientist13** [thegreenhouseio/www.thegreenhouse.io#43]
http://jenkins.thegreenhouse.io:8080/job/www.thegreenhouse.io/job/master/49/console
```
FAILED: on index.html invalidation request
{ InvalidArgument: Your request contains one or more invalid invalidation paths.
    at Request.extractError (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ubuntu/.jenkins/workspace/www.thegreenhouse.io_master-6NYPMGOBOHOOEGFL6OHEI7JL5Y3UN5Q22VDFO44SGG2Y5A4CDRMA/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Your request contains one or more invalid invalidation paths.',
  code: 'InvalidArgument',
  time: 2018-04-22T18:49:57.378Z,
  requestId: 'f3f591c2-465d-11e8-85be-cb8f346fcb09',
  statusCode: 400,
  retryable: false,
  retryDelay: 16.447280516136264 } 
```

naturally, this doesn't trigger cache busting in CloudFront.

**Comment by thescientist13** [comment]
looks like I need to provide a `/` in an invalidate pattern, e.g. `/*`
https://forums.aws.amazon.com/thread.jspa?threadID=98964
